apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uun04cf64-dotnet-basic
  janus-idp.io/tekton: uun04cf64-dotnet-basic
  backstage.io/kubernetes-id: uun04cf64-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uun04cf64-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
